### ISSUE TITLE
Compiler error use of deleted function luabridge::TypeResult<T>::TypeResult(...)

### ISSUE THREAD

**Issue by tsilia** [kunitoki/LuaBridge3#157]
Hello.

When building the project, compiler fails with the following error (I'm using GCC 9.4.0 on Ubuntu 20 to build the project with all submodules):

```
In file included from /home/user/LuaBridge3/Source/LuaBridge/LuaBridge.h:26,
                 from /home/user/LuaBridge3/Tests/Source/TestBase.h:12,
                 from /home/user/LuaBridge3/Tests/Source/Tests.cpp:10:
/home/user/LuaBridge3/Source/LuaBridge/detail/Globals.h: In instantiation of ‘luabridge::TypeResult<U> luabridge::getGlobal(lua_State*, const char*) [with T = std::shared_ptr<{anonymous}::A>; lua_State = lua_State]’:
/home/user/LuaBridge3/Tests/Source/Tests.cpp:606:77:   required from here
/home/user/LuaBridge3/Source/LuaBridge/detail/Globals.h:27:12: error: use of deleted function ‘luabridge::TypeResult<T>::TypeResult(const luabridge::TypeResult<T>&) [with T = std::shared_ptr<{anonymous}::A>]’
   27 |     return result;
      |            ^~~~~~
In file included from /home/user/LuaBridge3/Source/LuaBridge/detail/Stack.h:13,
                 from /home/user/LuaBridge3/Source/LuaBridge/detail/CFunctions.h:14,
                 from /home/user/LuaBridge3/Source/LuaBridge/LuaBridge.h:19,
                 from /home/user/LuaBridge3/Tests/Source/TestBase.h:12,
                 from /home/user/LuaBridge3/Tests/Source/Tests.cpp:10:
/home/user/LuaBridge3/Source/LuaBridge/detail/Result.h:81:5: note: ‘luabridge::TypeResult<T>::TypeResult(const luabridge::TypeResult<T>&) noexcept [with T = std::shared_ptr<{anonymous}::A>]’ is implicitly deleted because its exception-specification does not match the implicit exception-specification ‘noexcept (false)’
   81 |     TypeResult(const TypeResult&) noexcept = default;
      |     ^~~~~~~~~~
```

Is there any way to fix it?
Thanks!

**Comment by kunitoki** [comment]
Thanks for reporting, can definately be fixed.

**Comment by kunitoki** [comment]
Should be fixed in 9f38547cdb5a6758b5e30a7ca00037e89557a264

**Comment by tsilia** [comment]
Thanks for the quick response and follow up!

Unfortunately, this didn't fix the issue for me, the error seems to persist:

```
In file included from /home/user/LuaBridge3/Source/LuaBridge/LuaBridge.h:26,
                 from /home/user/LuaBridge3/Tests/Source/TestBase.h:12,
                 from /home/user/LuaBridge3/Tests/Source/Tests.cpp:10:
/home/user/LuaBridge3/Source/LuaBridge/detail/Globals.h: In instantiation of ‘luabridge::TypeResult<U> luabridge::getGlobal(lua_State*, const char*) [with T = std::shared_ptr<{anonymous}::A>; lua_State = lua_State]’:
/home/user/LuaBridge3/Tests/Source/Tests.cpp:606:77:   required from here
/home/user/LuaBridge3/Source/LuaBridge/detail/Globals.h:27:12: error: use of deleted function ‘luabridge::TypeResult<T>::TypeResult(const luabridge::TypeResult<T>&) [with T = std::shared_ptr<{anonymous}::A>]’
   27 |     return result;
      |            ^~~~~~
In file included from /home/user/LuaBridge3/Source/LuaBridge/detail/Stack.h:13,
                 from /home/user/LuaBridge3/Source/LuaBridge/detail/CFunctions.h:14,
                 from /home/user/LuaBridge3/Source/LuaBridge/LuaBridge.h:19,
                 from /home/user/LuaBridge3/Tests/Source/TestBase.h:12,
                 from /home/user/LuaBridge3/Tests/Source/Tests.cpp:10:
/home/user/LuaBridge3/Source/LuaBridge/detail/Result.h:83:5: note: ‘luabridge::TypeResult<T>::TypeResult(const luabridge::TypeResult<T>&) noexcept [with T = std::shared_ptr<{anonymous}::A>]’ is implicitly deleted because its exception-specification does not match the implicit exception-specification ‘noexcept (false)’
   83 |     TypeResult(const TypeResult&) noexcept(std::is_nothrow_copy_constructible_v<T>) = default;
      |     ^~~~~~~~~~
```

Correct me pls if I'm wrong, but I just did the following:
`git pull origin`
`rm -rf build`
`mkdir build && cd build`
`cmake ../ && cmake --build .`
Also, I made sure that `git log` output contains this commit: [`9f38547cdb5a6758b5e30a7ca00037e89557a264`](https://github.com/kunitoki/LuaBridge3/commit/9f38547cdb5a6758b5e30a7ca00037e89557a264)

**Comment by kunitoki** [comment]
I see, will patch it later

**Comment by kunitoki** [comment]
Could you retry latest master ?

**Comment by tsilia** [comment]
Thank you, the code now compiles successfully!
